#!/usr/bin/env python3
"""Scaffold a new document type for the DocuMind pipeline.

Generates the YAML config and prompt template files needed to add a new
doc type.  After running, the pipeline will auto-discover the new type
on next startup.

Usage::

    python scripts/add_doctype.py invoice "Invoice" --tasks summarize extract_clauses
    python scripts/add_doctype.py report "Audit Report" --formats pdf docx xlsx
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

# Resolve project paths
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
_TYPES_DIR = _PROJECT_ROOT / "src" / "documind" / "doctypes" / "types"
_PROMPTS_DIR = _PROJECT_ROOT / "src" / "documind" / "agents" / "analysis" / "prompts"
_SAMPLES_DIR = _PROJECT_ROOT / "samples"

# Known analysis tasks and their default prompt filenames
_KNOWN_TASKS = {
    "summarize": {
        "prompt_template": "{name}-summary.txt",
        "description": "Generate an executive summary of the {display_name}.",
    },
    "extract_clauses": {
        "prompt_template": "{name}-clauses.txt",
        "description": "Extract and categorise clauses from the {display_name}.",
    },
    "compliance_check": {
        "prompt_template": "{name}-compliance.txt",
        "description": "Check the {display_name} for completeness and standards compliance.",
    },
}

_DEFAULT_FORMATS = ["pdf", "docx"]


def _build_yaml(
    name: str,
    display_name: str,
    description: str,
    formats: list[str],
    tasks: list[str],
) -> str:
    """Generate the YAML config string for a new doc type."""
    lines = [
        f"# DocuMind — {display_name} document type",
        f"# Auto-generated by scripts/add_doctype.py",
        "",
        f"name: {name}",
        f'display_name: "{display_name}"',
        f"description: >",
        f"  {description}",
        f'version: "1.0"',
        "",
        "supported_formats:",
    ]
    for fmt in formats:
        lines.append(f"  - {fmt}")

    lines += [
        "",
        "doc_intelligence_model: prebuilt-layout",
        "",
        "extraction_fields: []",
        "",
        "analysis_tasks:",
    ]
    for task in tasks:
        info = _KNOWN_TASKS.get(task, {
            "prompt_template": f"{name}-{task}.txt",
            "description": f"Run {task} analysis on the {display_name}.",
        })
        template = info["prompt_template"].format(name=name, display_name=display_name)
        desc = info["description"].format(name=name, display_name=display_name)
        lines += [
            f"  - name: {task}",
            f"    prompt_template: {template}",
            f'    description: "{desc}"',
        ]

    lines += [
        "",
        "search_field_mappings: []",
        "",
        "enabled: true",
    ]
    return "\n".join(lines) + "\n"


def _build_prompt(name: str, display_name: str, task: str) -> str:
    """Generate a starter prompt template for a task."""
    return textwrap.dedent(f"""\
        You are an expert document analyst. Analyze the following {display_name} document.

        Task: {task}

        Respond with a JSON object containing your analysis.

        --- DOCUMENT START ---
        {{{{ document_text }}}}
        --- DOCUMENT END ---
    """)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Scaffold a new DocuMind document type.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("name", help="Doc-type identifier (lowercase, e.g. 'invoice').")
    parser.add_argument("display_name", help="Human-friendly name (e.g. 'Invoice').")
    parser.add_argument(
        "--description",
        default="",
        help="Short description of the document type.",
    )
    parser.add_argument(
        "--formats",
        nargs="+",
        default=_DEFAULT_FORMATS,
        help=f"Supported file formats (default: {_DEFAULT_FORMATS}).",
    )
    parser.add_argument(
        "--tasks",
        nargs="+",
        default=["summarize"],
        help="Analysis tasks to include (default: summarize).",
    )

    args = parser.parse_args(argv)
    name: str = args.name.lower().replace(" ", "_").replace("-", "_")
    display_name: str = args.display_name
    description: str = args.description or f"{display_name} documents processed by DocuMind."

    created: list[str] = []

    # 1. Write YAML config
    yaml_path = _TYPES_DIR / f"{name}.yaml"
    if yaml_path.exists():
        print(f"ERROR: {yaml_path} already exists. Remove it first or choose a different name.")
        return 1

    yaml_content = _build_yaml(name, display_name, description, args.formats, args.tasks)
    yaml_path.write_text(yaml_content, encoding="utf-8")
    created.append(str(yaml_path.relative_to(_PROJECT_ROOT)))

    # 2. Write prompt templates
    for task in args.tasks:
        info = _KNOWN_TASKS.get(task, {"prompt_template": f"{name}-{task}.txt"})
        template_name = info["prompt_template"].format(name=name, display_name=display_name)
        prompt_path = _PROMPTS_DIR / template_name

        if not prompt_path.exists():
            prompt_content = _build_prompt(name, display_name, task)
            prompt_path.write_text(prompt_content, encoding="utf-8")
            created.append(str(prompt_path.relative_to(_PROJECT_ROOT)))

    # 3. Create samples directory
    samples_path = _SAMPLES_DIR / f"{name}s"
    if not samples_path.exists():
        samples_path.mkdir(parents=True, exist_ok=True)
        gitkeep = samples_path / ".gitkeep"
        gitkeep.write_text("", encoding="utf-8")
        created.append(str(samples_path.relative_to(_PROJECT_ROOT)))

    print(f"\n✔ Doc type '{name}' scaffolded. Files created:")
    for f in created:
        print(f"    {f}")
    print(f"\nNext steps:")
    print(f"  1. Edit {yaml_path.relative_to(_PROJECT_ROOT)} — add extraction_fields and search_field_mappings")
    print(f"  2. Refine prompt templates in {_PROMPTS_DIR.relative_to(_PROJECT_ROOT)}/")
    print(f"  3. Drop sample documents in {samples_path.relative_to(_PROJECT_ROOT)}/")
    print(f"  4. Restart the pipeline — the new type is auto-discovered")

    return 0


if __name__ == "__main__":
    sys.exit(main())
